### ISSUE TITLE
Simplify the creation of a new kata project

### ISSUE THREAD

**Issue by VasileUngureanu** [codurance-apprenticeship/scripts#2]
Hi,

Thanks for this repository, which inspired me to create something similar for my personal needs!

I want to purpose you a simplified way (at least in my opinion) to create a new kata project:
We can just run:
```sh
sh -c "$(curl -fsSL https://URL link to script)"
```
The advantages are that we will not have download and copy/multiply scripts to various folders.  

To be more clear what I mean, please look at the real implementation of this proposal:
https://github.com/VasileUngureanu/kata-scripts

**Comment by sherlockq** [comment]
Thanks @VasileUngureanu , it's a great idea. I've updated the document and glad you enjoy this project.
